"""One place that decides how real a number is.

Provenance depends on **two** independent facts — whether the catalog is real, and
whether the event stream is real — so it cannot be derived from events alone. A real
catalog with a simulated event log is a genuinely different claim from a fully
invented dataset, and squashing them into one label would overstate the second or
understate the first.
"""

from __future__ import annotations

from app.domain.enums import Provenance


def resolve_provenance(
    *,
    catalog_total: int,
    catalog_synthetic: int,
    events_total: int,
    events_synthetic: int,
) -> Provenance:
    if not catalog_total and not events_total:
        return Provenance.REAL

    catalog_all_real = catalog_synthetic == 0
    catalog_all_synthetic = catalog_total > 0 and catalog_synthetic == catalog_total
    events_all_real = events_synthetic == 0
    events_all_synthetic = events_total > 0 and events_synthetic == events_total

    if catalog_all_real and (events_all_real or not events_total):
        return Provenance.REAL
    if catalog_all_real and events_all_synthetic:
        # The strongest honest claim available with a real catalog and no real log.
        return Provenance.SIMULATED_FROM_REAL_CATALOG
    if catalog_all_synthetic and events_all_synthetic:
        return Provenance.SYNTHETIC_SIMULATION
    return Provenance.MIXED


#: Human-readable disclosure for each state. Attached to reports so the caller never
#: has to interpret the enum themselves.
NOTICES: dict[Provenance, str] = {
    Provenance.REAL: (
        "Computed from the real catalog and real logged activity. Sample sizes and "
        "confidence labels are on every row."
    ),
    Provenance.SIMULATED_FROM_REAL_CATALOG: (
        "The catalog and its aggregate metrics (plays, likes, rating) are the platform's "
        "REAL data. The per-listener event stream is SIMULATED and calibrated to those "
        "aggregates, because the catalog records totals rather than individual events. "
        "Relative demand between titles is therefore meaningful; individual listener "
        "behaviour is not real and must not be quoted as such."
    ),
    Provenance.SYNTHETIC_SIMULATION: (
        "Every figure here is computed from a SYNTHETIC catalog and SYNTHETIC activity "
        "generated by this repository for pipeline testing. These are not real listeners "
        "and must not be presented as market truth."
    ),
    Provenance.MIXED: (
        "This report mixes real and synthetic records. Filter to real-only data before "
        "using it for any real decision."
    ),
}


def notice(provenance: Provenance) -> str:
    return NOTICES[provenance]
